version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install packages
          command: npm install
      - run:
          name: The First Step
          command: eslint 'src/**'
      - run:
          name: The Second Step
          command: npm run test:coveralls