jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run:
          name: eslint
          command: eslint 'src/**'
      - run:
          name: coveralls
          command: npm run test:coveralls